services:
  rocm:
    build:
      context: .
      args:
        APT_PREF: "Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600"
        AMDGPU_ARCH: "gfx1100"
        AMDGPU_VERSION: "6.3"
        ROCM_VERSION: "6.3"
    image: "schnaggelz:rocm"
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    container_name: rocm_server
    stdin_open: true
    tty: true
    env_file: ".env.rocm"
    ports:
      - "8888:8080"
    